apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  otel-collector-config.yaml:
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: "kwok-prometheus"
              scrape_interval: 10s
              static_configs:
                - targets: ["https://088a-149-156-124-14.ngrok-free.app"]

    exporters:
      logging:
        loglevel: debug
      prometheus:
        endpoint: "0.0.0.0:8889"

    processors:
      batch: {}

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch]
          exporters: [logging, prometheus]

